### PR TITLE
Gx update

### PR DESCRIPTION
**Pull request by ZenGround0**
Updating libp2p in deps to match version used by go-ipfs to eliminate dex import errors in ipfs-cluster

### CODE REVIEW

**Comment by hsanjuan** [comment]
@ZenGround0 I don't obtain the same hash when I gx publish myself. And tests are failing.

**Comment by hsanjuan** [comment]
And I can't get that hash so can't compare

**Comment by hsanjuan** [comment]
might need to update go version in travis for the tests

**Comment by ZenGround0** [comment]
@hsanjuan the tests are fixed and my daemon will be online all day hosting the gx pin if you'd like to compare

**Comment by hsanjuan** [comment]
THANKS @ZenGround0

**Pull request merged**
